# Site settings
title: "David J. Matthews"
description: "David J. Matthews &mdash; Creativity in Engineering"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "David J. Matthews"
resume_title:                   "Creativity in Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "DjmPhysics@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       ""
# resume_contact_address:         ""
resume_header_contact_info:     "<a href=\"mailto:DjmPhysics@gmail.com\">DjmPhysics@gmail.com</a>"
display_header_contact_info:    "true"

resume_header_intro: "<p>Scientific software engineer with extensive experience in the semiconductor industry.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
sections:
  - experience
  - education
  - projects
  - publications
  # - interests
  # - links

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dirtbirb"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/djmphysics"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://dirtbirb.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
